### ISSUE TITLE
Fasada powinna delegować, a nie posiadać logikę

### ISSUE THREAD

**Issue by tahonaPL** [jakubnabrdalik/hentai#2]
https://github.com/jakubnabrdalik/hentai/blob/b49e4610b09a3c51a11cdbd8524e211c904727fc/hentai/src/main/java/eu/solidcraft/film/domain/FilmFacade.java#L13

Wprowadzasz w błąd.

**Comment by jakubnabrdalik** [comment]
Ja tu żadnej logiki nie widzę, tylko delegację.
