### ISSUE TITLE
Pytanie. 

### ISSUE THREAD

**Issue by tahonaPL** [jakubnabrdalik/hentai#3]
https://github.com/jakubnabrdalik/hentai/blob/b49e4610b09a3c51a11cdbd8524e211c904727fc/hentai/src/main/java/eu/solidcraft/film/domain/FilmFacade.java#L13

Gdzie umieściłbyś abstrakcje do zewnętrznego serwisu? Np. pobieranie filmów z jakiegoś external provider'a.

**Comment by jakubnabrdalik** [comment]
Jeśli chcesz porozmawiać o architekturze, to można mnie spotkać na warsztatach z architektury lub na wykładach na różnych konferencjach.
Jeśli chcesz jednozdaniową odpowiedź na jednozdaniowe pytanie, to obawiam się że tak można jedynie wprowadzić w błąd. 
Architektura to nie jest system binarny, tylko gra trade-off'ów.
