### ISSUE TITLE
Question: FilmNotFoundException inside FilmRepository ?

### ISSUE THREAD

**Issue by ppretki** [jakubnabrdalik/hentai#5]
Wouldn't be better to leave domain (**FilmRepository**) free from DTO concepts (**FilmNotFoundException**) ? i.e.:

```
interface FilmRepository extends Repository<Film, String> {
    Film save(Film film);
    Optional<Film> findByTitle(String title);
    Page<Film> findAll(Pageable pageable);
}

```
and throw **FilmNotFoundException** from **FilmFacade**:

```
public FilmDto show(String filmTitle) {
        requireNonNull(filmTitle);
        return filmRepository.findByTitle(filmTitle)
                             .map(Film::dto)
                             .orElseThrow(() -> new FilmNotFoundException(filmTitle));
}

```

**Comment by CamilYed** [comment]
I would also rename package dto to api. 
The exception is not pure DTO object.

**Comment by jakubnabrdalik** [comment]
@ppretki  this makes very little difference IMO, because the the DTOs are a public contract owned by the module (in this case). But throwing an exception has bad performance anyway, so if we were doing it at work, I'd change that anyway.

@KamilJedrzejuk  while not pure, it also transfers information. It's just that Java has two ways of returning information from a method: either with returned value or with an exception. 
Anyway, I'm not religious about it. For example my latest microservice has 
```
/api
- incomingEventsApi.kt
- outgoingEventsApi.kt
```
So you'd be happy I think :)

**Comment by jakubnabrdalik** [comment]
Perhaps I should update this example. I have more with Kofu, Testcontainers etc. :) I'll see before the next workshop.

**Comment by CamilYed** [comment]
> @ppretki this makes very little difference IMO, because the the DTOs are a public contract owned by the module (in this case). But throwing an exception has bad performance anyway, so if we were doing it at work, I'd change that anyway.
> 
> @KamilJedrzejuk while not pure, it also transfers information. It's just that Java has two ways of returning information from a method: either with returned value or with an exception.
> Anyway, I'm not religious about it. For example my latest microservice has
> 
> ```
> /api
> - incomingEventsApi.kt
> - outgoingEventsApi.kt
> ```
> 
> So you'd be happy I think :)

Kotlin does not have a package scope...
BTW now in allegro my team use this approach https://allegro.tech/2020/05/hexagonal-architecture-by-example.html ...

**Comment by jakubnabrdalik** [comment]
> Kotlin does not have a package scope...

Thanks to @0xKKocel and with my full support
https://youtrack.jetbrains.com/issue/KT-32886

> BTW now in allegro my team use this approach https://allegro.tech/2020/05/hexagonal-architecture-by-example.html ...

It's sad that Allegro has so poor internal knowledge propagation. We've been doing it since 2015 :)

**Comment by CamilYed** [comment]
Now - because I ve started new job at allegro :) But I believe ;)
